# argocd make k8s applying deployment by using this yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-test
  template:
    metadata:
      labels:
        app: cicd-test
    spec:
      containers:
      - name: cicd-test
        image: crpi-xb7f9irfobdd1w7v.cn-hangzhou.personal.cr.aliyuncs.com/canlia-sre/ci_test:d70e0c0393d7ebc615be092b31855229849351bb
        ports:
        - containerPort: 8888
      imagePullSecrets:
      - name: aliyun-registry-secret
