name: SRE Pipeline

on:
  push:
    branches: [ "main" ]
  push_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: 1. 拉取仓库代码
      uses: actions/checkout@v3

    - name: 2. 安装 Go 语言环境
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: 3. 执行自动化测试
      run: go test ./...

    - name: 4. 模拟打包并打印防伪码
      run: |
        echo "代码测试全部通过！"
        echo "准备构建的镜像防伪码是: ${{ github.sha }}"
