name: SRE Pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'deploy/**'
      - '.github/**'
      - 'README.md' 
  pull_request:
    branches: [ "main" ]

# 赋予机器人修改代码仓库的写权限
permissions:
  contents: write
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: 1. 拉取仓库代码
      uses: actions/checkout@v3

    - name: 2. 安装 Go 语言环境
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: 3. 执行自动化测试 (所有阶段都会执行)
      run: go test ./...

    # 🚨 核心分水岭：下面的步骤，只有代码真正并入 main 分支时才会执行！
    # 提 PR 时，流水线走到上一步测试通过就结束了，绝不制造垃圾镜像。
    - name: 4. 登录阿里云 ACR
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        docker login -u "${{ secrets.ALIYUN_REGISTRY_USER }}" -p "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" crpi-xb7f9irfobdd1w7v.cn-hangzhou.personal.cr.aliyuncs.com

    - name: 5. 注入防伪码并推上云端
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        IMAGE_TAG: ${{ github.sha }}
        REPO_URL: crpi-xb7f9irfobdd1w7v.cn-hangzhou.personal.cr.aliyuncs.com/canlia-sre/ci_test
      run: |
        echo "开始构建镜像: $REPO_URL:$IMAGE_TAG"
        docker build -t $REPO_URL:$IMAGE_TAG .
        
        echo "开始推送镜像至阿里云..."
        docker push $REPO_URL:$IMAGE_TAG
        
        echo "🎉 镜像推送成功！请去阿里云控制台查收防伪码: $IMAGE_TAG"
    - name: 6. [CI/CD 桥接] 自动修改 YAML 并推送到 GitHub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        # 配置机器人的 Git 身份
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # 定义变量
        IMAGE_URL="crpi-xb7f9irfobdd1w7v.cn-hangzhou.personal.cr.aliyuncs.com/canlia-sre/ci_test"

        # 暴力替换 deployment.yaml 中的 image 字段为最新防伪码
        sed -i "s|image: .*|image: ${IMAGE_URL}:${{ github.sha }}|g" deploy/deployment.yaml

        # 机器人提交代码
        git add deploy/deployment.yaml
        git commit -m "🤖 CD Trigger: update image tag to ${{ github.sha }}"
        git push
